# Generated by Django 4.0.1 on 2022-02-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_num',
            field=models.CharField(max_length=10),
        ),
    ]
