# Generated by Django 4.0.1 on 2022-02-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_user_mobile_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(auto_created=True, max_length=1000, primary_key=True, serialize=False),
        ),
    ]
