# Generated by Django 4.0.1 on 2022-02-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(auto_created=True, max_length=1000, primary_key=True, serialize=False),
        ),
    ]
