# Generated by Django 4.0.1 on 2022-02-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0005_alter_post_dislikes_count_alter_post_likes_counts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
