# Generated by Django 4.0.1 on 2022-02-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0003_alter_comment_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
